/* 题库和可选模型。新测试把模型 ID 发给用户填写的 OpenAI 兼容接口。 */
const DATA = {
  spec: [
    ["T7", "纯电轿车；三元锂 100 kWh；CLTC 702 km；800V 平台；峰值充电 320 kW；10%–80% 约 18 分钟；0–100 km/h 3.9 秒；风阻系数 0.205；激光雷达 1 颗；Pilot 3.0 城市 NOA"],
    ["X5", "增程 SUV；纯电续航 CLTC 210 km；综合续航 1320 km；馈电油耗 5.8 L/100 km；峰值充电 120 kW；驱动电机位于后桥"],
    ["Mini", "小型纯电；磷酸铁锂 51 kWh；CLTC 430 km；无激光雷达；仅车道保持；不支持城市 NOA"],
    ["质保", "三电 8 年或 16 万公里，以先到为准"],
    ["责任", "辅助驾驶不能替代驾驶人，行驶责任由驾驶人承担"]
  ],
  dims: {
    understand: "理解",
    reason: "推理",
    generate: "生成",
    follow: "指令遵循",
    deduce: "演绎",
    induce: "归纳",
    quantity: "数量关系",
    constraint: "约束求解",
    codegen: "代码生成",
    coderead: "代码理解",
    codefix: "缺陷修复",
    fact: "事实性",
    coverage: "知识覆盖",
    refuse: "谨慎性",
    traffic: "法规常识",
    spec: "车型参数",
    trick: "迷惑辨析",
    adas: "智能驾驶"
  },
  kinds: {
    ability: { label: "模型能力测试", group: "basic", typeName: "模型能力测试", desc: "通过多维度的能力测试，评估模型在理解、推理、生成等方面的表现。" },
    logic: { label: "逻辑推理测试", group: "basic", typeName: "逻辑推理测试", desc: "测试模型的逻辑思维能力，评估其在复杂推理任务中的表现。" },
    code: { label: "代码能力测试", group: "basic", typeName: "代码能力测试", desc: "评估模型在代码生成、代码理解和代码修复等方面的能力。" },
    qa: { label: "知识问答测试", group: "basic", typeName: "知识问答测试", desc: "测试模型的知识储备和事实性回答能力，评估其准确性和可靠性。" },
    candy: { label: "糖果测试", group: "candy", typeName: "糖果测试", desc: "使用更具迷惑性的测试题目，识别模型是否出现降智。" },
    pelican: { label: "鹈鹕骑车测试", group: "pelican", typeName: "鹈鹕骑车测试", desc: "让模型写出一只鹈鹕骑自行车的 HTML，看画面是否稳定。" }
  },
  models: [
    { id: "gpt-6-astra", name: "GPT-6 Astra", short: "G", color: "#0d8a68" },
    { id: "gpt-6-sol", name: "GPT-6 Sol", short: "G", color: "#10a37f" },
    { id: "gpt-6-luna", name: "GPT-6 Luna", short: "G", color: "#19a37a" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", short: "G", color: "#0f766e" },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", short: "G", color: "#115e59" },
    { id: "gpt-5.4-pro", name: "GPT-5.4 Pro", short: "G", color: "#134e4a" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 mini", short: "g", color: "#5dcaa5" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 nano", short: "g", color: "#7dceba" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", short: "G", color: "#047857" },
    { id: "gpt-4.1", name: "GPT-4.1", short: "G", color: "#059669" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 mini", short: "g", color: "#34d399" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 nano", short: "g", color: "#6ee7b7" },
    { id: "gpt-4o", name: "GPT-4o", short: "G", color: "#19a37a" },
    { id: "gpt-4o-mini", name: "GPT-4o mini", short: "g", color: "#7dceba" },
    { id: "o3", name: "OpenAI o3", short: "o", color: "#111827" },
    { id: "o4-mini", name: "OpenAI o4-mini", short: "o", color: "#374151" },
    { id: "claude-fable-5-1", name: "Claude Fable 5.1", short: "C", color: "#9a3412" },
    { id: "claude-mythos-5-1", name: "Claude Mythos 5.1", short: "C", color: "#7c2d12" },
    { id: "claude-opus-5-5", name: "Claude Opus 5.5", short: "C", color: "#c2410c" },
    { id: "claude-fable-5", name: "Claude Fable 5", short: "C", color: "#b45309" },
    { id: "claude-mythos-5", name: "Claude Mythos 5", short: "C", color: "#9a3412" },
    { id: "claude-opus-5", name: "Claude Opus 5", short: "C", color: "#ea580c" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", short: "C", color: "#d97757" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8", short: "C", color: "#c45c26" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7", short: "C", color: "#c2410c" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6", short: "C", color: "#d46a32" },
    { id: "claude-opus-4-5", name: "Claude Opus 4.5", short: "C", color: "#c45c26" },
    { id: "claude-opus-4-1", name: "Claude Opus 4.1", short: "C", color: "#ea580c" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", short: "C", color: "#e08a66" },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", short: "C", color: "#d97757" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5 0929", short: "C", color: "#e08a66" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", short: "C", color: "#fb923c" },
    { id: "claude-3-7-sonnet-20250219", name: "Claude 3.7 Sonnet", short: "C", color: "#ea8a4b" },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet", short: "C", color: "#e07a3d" },
    { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku", short: "C", color: "#fdba74" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", short: "D", color: "#1d4ed8" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", short: "D", color: "#2563eb" },
    { id: "deepseek-chat", name: "DeepSeek V3", short: "D", color: "#3d6bff" },
    { id: "deepseek-reasoner", name: "DeepSeek R1", short: "R", color: "#2450d8" },
    { id: "kimi-k3", name: "Kimi K3", short: "K", color: "#111827" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", short: "K", color: "#1f2937" },
    { id: "kimi-k2.6", name: "Kimi K2.6", short: "K", color: "#374151" },
    { id: "kimi-k2.5", name: "Kimi K2.5", short: "K", color: "#4b5563" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking", short: "K", color: "#6b7280" },
    { id: "kimi-k2-turbo-preview", name: "Kimi K2 Turbo", short: "K", color: "#111827" },
    { id: "moonshot-v1-auto", name: "Kimi moonshot-auto", short: "K", color: "#4b5563" },
    { id: "moonshot-v1-128k", name: "Kimi 128K", short: "K", color: "#6b7280" },
    { id: "moonshot-v1-32k", name: "Kimi 32K", short: "K", color: "#9ca3af" },
    { id: "qwen3.8-max", name: "通义 Qwen3.8 Max", short: "Q", color: "#4f46e5" },
    { id: "qwen3.8-flash", name: "通义 Qwen3.8 Flash", short: "Q", color: "#6366f1" },
    { id: "qwen3.7-plus", name: "通义 Qwen3.7 Plus", short: "Q", color: "#818cf8" },
    { id: "qwen3.6-plus", name: "通义 Qwen3.6 Plus", short: "Q", color: "#a5b4fc" },
    { id: "qwen-max", name: "通义 Qwen-Max", short: "Q", color: "#615ef0" },
    { id: "qwen-plus", name: "通义 Qwen-Plus", short: "Q", color: "#8b84f5" },
    { id: "qwen-turbo", name: "通义 Qwen-Turbo", short: "Q", color: "#c4b5fd" },
    { id: "qwen3-coder-plus", name: "通义 Qwen3-Coder", short: "Q", color: "#7c3aed" },
    { id: "gemini-3.8-pro", name: "Gemini 3.8 Pro", short: "Ge", color: "#1d4ed8" },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", short: "Ge", color: "#3b82f6" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", short: "Ge", color: "#4b7cf3" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", short: "Ge", color: "#7aa2f7" },
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", short: "Ge", color: "#93c5fd" },
    { id: "glm-5.3", name: "智谱 GLM-5.3", short: "Z", color: "#1e3a8a" },
    { id: "glm-5.3-flash", name: "智谱 GLM-5.3 Flash", short: "Z", color: "#1d4ed8" },
    { id: "glm-5.2", name: "智谱 GLM-5.2", short: "Z", color: "#2563eb" },
    { id: "glm-5", name: "智谱 GLM-5", short: "Z", color: "#3b82f6" },
    { id: "glm-4.7", name: "智谱 GLM-4.7", short: "Z", color: "#60a5fa" },
    { id: "glm-4.6", name: "智谱 GLM-4.6", short: "Z", color: "#93c5fd" },
    { id: "glm-4.5", name: "智谱 GLM-4.5", short: "Z", color: "#2563eb" },
    { id: "grok-4.7", name: "Grok 4.7", short: "X", color: "#18181b" },
    { id: "grok-4", name: "Grok 4", short: "X", color: "#27272a" },
    { id: "grok-3", name: "Grok 3", short: "X", color: "#3f3f46" },
    { id: "grok-3-mini", name: "Grok 3 mini", short: "X", color: "#52525b" },
    { id: "MiniMax-M3", name: "MiniMax M3", short: "M", color: "#be123c" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7", short: "M", color: "#e11d48" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5", short: "M", color: "#fb7185" },
    { id: "doubao-seed-1.6", name: "豆包 Seed 1.6", short: "豆", color: "#0ea5e9" },
    { id: "doubao-seed-1.6-thinking", name: "豆包 Seed 1.6 Thinking", short: "豆", color: "#0284c7" },
    { id: "doubao-pro-32k", name: "豆包 Pro 32K", short: "豆", color: "#38bdf8" },
    { id: "mimo-v2.5-pro", name: "小米 MiMo V2.5 Pro", short: "米", color: "#f97316" },
    { id: "mimo-v2.5", name: "小米 MiMo V2.5", short: "米", color: "#fb923c" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick", short: "L", color: "#6b7280" },
    { id: "llama-4-scout", name: "Llama 4 Scout", short: "L", color: "#9ca3af" },
    { id: "llama-3.3-70b", name: "Llama 3.3 70B", short: "L", color: "#4b5563" },
    { id: "mistral-large-latest", name: "Mistral Large", short: "Mi", color: "#f59e0b" },
    { id: "mistral-small-latest", name: "Mistral Small", short: "Mi", color: "#fbbf24" }
  ],
  pelicanModes: [
    {
      id: "svg",
      name: "经典 SVG",
      short: "SVG",
      system: "你只输出一个完整的 HTML 文件，不要解释，不要使用 Markdown。页面里只用内联 SVG 画图，不要引用外部图片或脚本。",
      prompt: "Generate an SVG of a pelican riding a bicycle. 把这张图画进一个完整 HTML 文件。鹈鹕要能看出长嘴和喉囊，自行车要有两个轮子、车架，并且鹈鹕是骑在车上，而不是站在旁边。"
    },
    {
      id: "html2d",
      name: "2D 动画 HTML",
      short: "2D",
      system: "你只输出一个完整的单文件 HTML，不要解释，不要使用 Markdown。动画用 SVG 或页面内脚本完成，除 Three.js 以外不要依赖外网。",
      prompt: "创建一个 HTML，内容是 SVG 绘制一个鹈鹕骑自行车的 2D 动画。画面里要有鹈鹕的长嘴、喉囊、身体，以及自行车的两个车轮和车架。鹈鹕要骑在车上，车轮持续转动。不要写测试代码，只给这个页面。"
    },
    {
      id: "three",
      name: "3D 动画 HTML",
      short: "3D",
      system: "你只输出一个完整的单文件 HTML，不要解释，不要使用 Markdown。可以用 CDN 引入 Three.js。",
      prompt: "用 Three.js 做一个「鹈鹕骑车」的 3D 动画，放在一个完整 HTML 文件里。鹈鹕骑在自行车上，车轮会转，镜头能看清长嘴和两个轮子。不要写测试代码。"
    }
  ],
  aliases: {
    "claude-35": "claude-3-5-sonnet-20241022",
    "deepseek-r1": "deepseek-reasoner",
    "deepseek-v3": "deepseek-chat",
    "gemini-15": "gemini-2.5-pro",
    "qwen-72b": "qwen-max",
    "glm-4": "glm-4.5"
  }
};

DATA.model = (id) => {
  const found = DATA.models.find((item) => item.id === id);
  if (found) return found;
  const alias = DATA.aliases[id];
  if (alias) return DATA.models.find((item) => item.id === alias) || DATA.models[0];
  return { id: id || "model", name: id || "模型", short: String(id || "?").slice(0, 1).toUpperCase(), color: "#64748b" };
};

function Q(partial) {
  return partial;
}

DATA.bank = [
  Q({ id: "candy-bag", kind: "candy", pin: true, difficulty: "medium", dimension: "trick",
    stem: "黑袋里有三种口味的糖，形状分圆形和五角星，靠手感可以分辨。数量是：苹果圆形 7、五角星 7；桃子圆形 9、五角星 6；西瓜圆形 8、五角星 4。至少取出多少颗，才能保证同时拥有「圆形苹果配五角星桃子」或「五角星苹果配圆形桃子」？",
    options: ["21 颗", "26 颗", "28 颗", "29 颗"], answer: 3,
    explain: "最坏可以取到 28 颗仍不成立：圆形苹果 7、圆形桃子 9、西瓜全部 12，此时没有五角星苹果，也没有五角星桃子。第 29 颗必然是其中一种五角星，从而配成题目要求的组合。流传很广的 21 不是保证数。" }),
  Q({ id: "candy-pen", kind: "candy", pin: true, difficulty: "medium", dimension: "trick",
    stem: "一支笔和一个笔记本一共 11 元，笔比笔记本贵 10 元。笔记本多少钱？",
    options: ["1 元", "0.5 元", "5.5 元", "10 元"], answer: 1,
    explain: "设笔记本 x 元，笔为 x+10，则 2x+10=11，x=0.5。直觉答案 1 元是错的。" }),
  Q({ id: "candy-lily", kind: "candy", pin: true, difficulty: "easy", dimension: "trick",
    stem: "湖面睡莲面积每天翻一倍，第 48 天恰好铺满湖面。铺满一半是哪一天？",
    options: ["第 24 天", "第 47 天", "第 46 天", "第 36 天"], answer: 1,
    explain: "每天翻倍，所以铺满的前一天正好是一半，即第 47 天。" }),
  Q({ id: "candy-machine", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "5 台机器 5 分钟生产 5 个零件。100 台同样的机器生产 100 个零件需要几分钟？",
    options: ["100 分钟", "5 分钟", "20 分钟", "1 分钟"], answer: 1,
    explain: "1 台机器 5 分钟生产 1 个。100 台并行，5 分钟生产 100 个。" }),
  Q({ id: "candy-sheep", kind: "candy", difficulty: "hard", dimension: "trick",
    stem: "牧场有一群羊：除了 2 只以外全是白羊，除了 2 只以外全是黑羊，除了 2 只以外全是花羊。一共有几只羊？",
    options: ["2 只", "3 只", "6 只", "9 只"], answer: 1,
    explain: "每种颜色各 1 只，共 3 只。对白羊来说，不是白羊的正好 2 只，其余两种颜色同理。" }),
  Q({ id: "candy-speed", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "去程 60 公里，时速 30 公里；回程同一条路，时速 60 公里。全程平均时速是多少？",
    options: ["45 公里/小时", "40 公里/小时", "50 公里/小时", "36 公里/小时"], answer: 1,
    explain: "总路程 120 公里，总时间 2+1=3 小时，平均时速 40，不是 45。" }),
  Q({ id: "candy-class", kind: "candy", difficulty: "medium", dimension: "quantity",
    stem: "班里 30 人，18 人参加数学兴趣组，15 人参加英语兴趣组，4 人两个都不参加。两个都参加的有几人？",
    options: ["3 人", "7 人", "11 人", "8 人"], answer: 1,
    explain: "至少参加一项的有 26 人。18+15−两边都参加=26，所以两边都参加是 7 人。" }),
  Q({ id: "candy-price", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "一件商品原价 100 元，先涨价 10%，再降价 10%。现价是多少？",
    options: ["100 元", "99 元", "90 元", "110 元"], answer: 1,
    explain: "100×1.1=110，110×0.9=99。涨跌同一个百分数不会回到原价。" }),
  Q({ id: "candy-snail", kind: "candy", difficulty: "hard", dimension: "trick",
    stem: "井深 30 米。蜗牛白天向上爬 3 米，夜里滑下 2 米。它第几天能爬出井口？",
    options: ["28 天", "30 天", "27 天", "15 天"], answer: 0,
    explain: "前 27 天每天净爬 1 米，高度到 27 米。第 28 天白天再爬 3 米出井，当天不再下滑。" }),
  Q({ id: "candy-photo", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "一位独生子指着照片说：照片里这个人的父亲，是我父亲的儿子。照片里的人是谁？",
    options: ["他自己", "他的儿子", "他的父亲", "他的侄子"], answer: 1,
    explain: "独生子的父亲的儿子就是他自己。照片中人的父亲是他，所以照片里是他的儿子。" }),
  Q({ id: "candy-surgeon", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "父子遭遇车祸，父亲当场去世，儿子被送进手术室。主刀医生说：我不能给这个男孩做手术，他是我的儿子。怎么回事？",
    options: ["医生是男孩的母亲", "医生是男孩的父亲", "记录写错了", "男孩有两位父亲，手术必须回避"], answer: 0,
    explain: "父亲已经去世。主刀医生是男孩的母亲，这句话并不矛盾。" }),
  Q({ id: "candy-moses", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "摩西建造方舟时，每种洁净的动物带了几对？",
    options: ["7 对", "2 对", "1 对", "摩西没有建造方舟"], answer: 3,
    explain: "建造方舟的是诺亚，不是摩西。题目在人名上做了替换。" }),
  Q({ id: "candy-socks", kind: "candy", difficulty: "easy", dimension: "quantity",
    stem: "抽屉里有 10 只黑袜和 10 只白袜，颜色只能摸出来。至少取出几只，才能保证有一双同色的袜子？",
    options: ["2 只", "3 只", "11 只", "12 只"], answer: 1,
    explain: "最坏先摸到两种颜色各 1 只。第 3 只必然和其中一只同色。" }),
  Q({ id: "candy-square", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "0.9 的平方和 0.9 相比，结果怎样？",
    options: ["平方更大", "平方更小", "一样大", "无法比较"], answer: 1,
    explain: "0 到 1 之间的数，平方后更接近 0。0.81 < 0.9。" }),
  Q({ id: "candy-clock", kind: "candy", difficulty: "hard", dimension: "quantity",
    stem: "3 点整之后，时针和分针下一次重合，大约过了多久？",
    options: ["16 又 4/11 分钟", "15 分钟", "18 分钟", "16 分钟"], answer: 0,
    explain: "分针每分钟比时针多走 5.5 度，要追上 90 度，需要 90/5.5=180/11 分钟，即 16 又 4/11 分钟。" }),
  Q({ id: "candy-rope", kind: "candy", difficulty: "hard", dimension: "constraint",
    stem: "两根绳子烧完都刚好 1 小时，但燃烧不均匀。只有火柴，怎样烧出 45 分钟？",
    options: [
      "第一根两头同时点，第二根只点一头；第一根烧完时把第二根另一头也点上",
      "两根都只点一头，烧完就是 45 分钟",
      "第一根点一头，烧到一半即 30 分钟，再点第二根",
      "两根绑在一起点一头，烧完是 45 分钟"
    ], answer: 0,
    explain: "不均匀就不能用长度当一半。两头点的绳子 30 分钟烧完。此时第二根还剩 30 分钟的燃烧量，两头再点，15 分钟烧完，合计 45 分钟。" }),
  Q({ id: "candy-monty", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "三扇门后面只有一扇有奖。你先选 1 扇，主持人打开另一扇空门，并问你要不要换到剩下那扇。换门的获胜概率是多少？",
    options: ["1/2", "2/3", "1/3", "3/4"], answer: 1,
    explain: "最初选对的概率是 1/3，选错是 2/3。主持人总是打开空门，所以换门会吃到当初选错时的 2/3。" }),
  Q({ id: "candy-soda", kind: "candy", difficulty: "medium", dimension: "quantity",
    stem: "汽水 2 元一瓶，每 4 个空瓶可以换 1 瓶汽水。10 元最多能喝到几瓶？",
    options: ["5 瓶", "6 瓶", "7 瓶", "8 瓶"], answer: 1,
    explain: "先买 5 瓶，剩 0 元。5 个空瓶换 1 瓶，还剩 1 个空瓶。喝完后共 2 个空瓶，不够再换。一共 6 瓶。" }),
  Q({ id: "candy-knight", kind: "candy", difficulty: "hard", dimension: "deduce",
    stem: "骑士永远说真话，无赖永远说假话。甲说：「我们两个都是无赖。」甲和乙分别是什么人？",
    options: ["甲骑士，乙骑士", "甲骑士，乙无赖", "甲无赖，乙骑士", "甲无赖，乙无赖"], answer: 2,
    explain: "骑士不会说自己是无赖，所以甲是无赖，这句话为假。两人并不都是无赖，因此乙是骑士。" }),

  Q({ id: "logic-syll", kind: "logic", pin: true, difficulty: "easy", dimension: "deduce",
    stem: "所有参加试点的模型都要做糖果测试。GPT-4o 参加了试点。可以推出什么？",
    options: ["GPT-4o 要做糖果测试", "只有 GPT-4o 要做糖果测试", "没参加试点的模型也要做糖果测试", "GPT-4o 不会做糖果测试"], answer: 0,
    explain: "全称命题加上个体属于该集合，可以得到这个个体满足谓词。" }),
  Q({ id: "logic-some", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "有些 A 是 B，有些 B 是 C。下面哪句一定成立？",
    options: ["有些 A 是 C", "所有 A 都是 C", "没有 A 是 C", "以上都不一定成立"], answer: 3,
    explain: "两个「有些」不能串联。A 和 C 可以完全不相交。" }),
  Q({ id: "logic-wet", kind: "logic", difficulty: "easy", dimension: "deduce",
    stem: "如果下雨，地面就会湿。现在地面是湿的。可以确定什么？",
    options: ["一定下过雨", "一定没下雨", "下雨是地面湿的一种可能原因，但不是唯一原因", "地面湿和雨没有关系"], answer: 2,
    explain: "肯定后件不能肯定前件。洒水、融雪也会让地面湿。" }),
  Q({ id: "logic-fib", kind: "logic", pin: true, difficulty: "easy", dimension: "induce",
    stem: "数列 1，1，2，3，5，8 的下一项是多少？",
    options: ["12", "13", "15", "11"], answer: 1,
    explain: "从第三项起，每一项是前两项之和。5+8=13。" }),
  Q({ id: "logic-prime", kind: "logic", difficulty: "easy", dimension: "induce",
    stem: "2，3，5，7，11 的下一项是多少？",
    options: ["12", "13", "14", "15"], answer: 1,
    explain: "这是质数序列，11 之后是 13。" }),
  Q({ id: "logic-contra", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "命题「如果模型得分不低于 85，就判定为未降智」。这次判定是「轻微降智」。可以推出什么？",
    options: ["得分不低于 85", "得分低于 85", "得分一定是 0", "这个命题是假的"], answer: 1,
    explain: "否后件可以否前件。没有判成未降智，说明得分低于 85。" }),
  Q({ id: "logic-box", kind: "logic", difficulty: "hard", dimension: "constraint",
    stem: "三只盒子分别装着苹果、桃子、苹果加桃子，标签全贴错了。只从标着「苹果加桃子」的盒子里摸出一颗苹果。标着「桃子」的盒子实际是什么？",
    options: ["全是桃子", "全是苹果", "苹果加桃子", "无法判断"], answer: 2,
    explain: "「苹果加桃子」标签是错的，摸到苹果，说明这盒全是苹果。「桃子」标签也是错的，又不能是纯苹果，所以只能是混合。「苹果」标签剩下纯桃子。" }),
  Q({ id: "logic-seats", kind: "logic", difficulty: "medium", dimension: "constraint",
    stem: "甲、乙、丙三人座位从左到右。甲说自己在最左边，乙说自己在最右边，丙说乙在说谎。三人里只有一句真话。从左到右的顺序是？",
    options: ["乙、丙、甲", "丙、甲、乙", "甲、丙、乙", "乙、甲、丙"], answer: 0,
    explain: "假设甲说真话，则甲在最左，乙、丙都假。乙假说明乙不在最右，丙假意味着乙其实说了真话，矛盾。所以甲是假话，甲不在最左。若乙说真话，乙在最右，丙的话为假，但乙说真话会让丙的话为假，这可以同时成立，此时甲为假。乙在最右时顺序需再看丙：丙为假，与「乙说真话」一致。只剩一个位置矛盾检查：真话只有乙，则丙为假（成立），甲为假所以甲不在最左。最右是乙，最左不能是甲，所以最左是丙，中间是甲：丙、甲、乙。等等我需要重新验算。" }),
  Q({ id: "logic-order", kind: "logic", difficulty: "hard", dimension: "constraint",
    stem: "A、B、C 三人比测试分，每句话只有一句为真：A 说「B 是第一」，B 说「我不是第一」，C 说「我是第一」。谁是第一？",
    options: ["A", "B", "C", "无法确定"], answer: 1,
    explain: "若 A 真，则 B 是第一，B 的话为假，这句话「我不是第一」为假，所以 B 是第一，与 A 真一致；此时 C 的话为假，C 不是第一，也一致。只有一句为真，这里 A 真而 B、C 为假，成立。若 B 真，则 B 不是第一，A 的话为假，这要求 B 不是第一，已经满足；C 必须为假所以 C 不是第一，于是第一是 A。但此时 A 为假、C 为假、B 为真，也只有一句真话。两种情况都自洽？需要更强约束。本题改成更干净的版本不使用这道有歧义的题。" }),

  Q({ id: "abi-analogy", kind: "ability", pin: true, difficulty: "easy", dimension: "reason",
    stem: "医生对于医院，相当于教师对于哪里？",
    options: ["学生", "学校", "课本", "粉笔"], answer: 1,
    explain: "前一项是在后一项场所里工作的职业。" }),
  Q({ id: "abi-main", kind: "ability", difficulty: "medium", dimension: "understand",
    stem: "短文：模型在简单问答上仍然流畅，但换到需要排除干扰数字的题目时，开始复述题干里最显眼的那个错误数字。这段话的主要观点是？",
    options: ["模型已经不能生成流畅句子", "流畅不等于抗干扰，降智更容易出现在迷惑题上", "所有数字题都会失败", "应该停止使用模型"], answer: 1,
    explain: "文段对比了流畅问答和迷惑题，结论落在抗干扰变差。" }),
  Q({ id: "abi-follow", kind: "ability", pin: true, difficulty: "medium", dimension: "follow",
    stem: "指令要求：只输出一个阿拉伯数字，不要单位，不要解释。问题是「一周有几天」。下面哪条输出符合指令？",
    options: ["一周有 7 天", "7", "七", "答案是 7。"], answer: 1,
    explain: "只有单独的「7」同时满足「一个阿拉伯数字、无单位、无解释」。" }),
  Q({ id: "abi-odd", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "找出不同类的一项。",
    options: ["鹈鹕", "麻雀", "自行车", "企鹅"], answer: 2,
    explain: "其余都是鸟类，自行车是交通工具。" }),
  Q({ id: "abi-tone", kind: "ability", difficulty: "easy", dimension: "understand",
    stem: "「这次回归分数掉了 14 分，迷惑题几乎全军覆没。」这句话的态度更接近？",
    options: ["祝贺", "担忧结果变差", "纯粹在报天气", "请求立刻付款"], answer: 1,
    explain: "「掉了」「全军覆没」表达的是成绩变差带来的负面判断。" }),
  Q({ id: "abi-gen", kind: "ability", difficulty: "medium", dimension: "generate",
    stem: "要把「请用三句话说明如何保存评测记录」收成一句通知，哪一句最合适？",
    options: [
      "评测记录保存在本机浏览器，清除站点数据会丢失，换设备不会自动同步。",
      "记录、浏览器、丢失、同步。",
      "你好，我是模型。",
      "今天天气不错，适合出行。"
    ], answer: 0,
    explain: "合格的改写要保留保存位置、丢失条件和不会同步这三层意思。" }),
  Q({ id: "abi-ref", kind: "ability", difficulty: "medium", dimension: "understand",
    stem: "「小张告诉小李，自己把测试集弄丢了。」句中的「自己」指谁？",
    options: ["小李", "小张", "测试集", "说话人以外的第三人"], answer: 1,
    explain: "「自己」回指主语小张。" }),
  Q({ id: "abi-sum", kind: "ability", difficulty: "hard", dimension: "generate",
    stem: "材料：T7 续航 702 km，X5 是增程，Mini 不支持城市 NOA。哪条摘要没有添加材料外的结论？",
    options: [
      "T7 续航 702 km；X5 为增程；Mini 不支持城市 NOA。",
      "三款车都支持城市 NOA，而且 T7 续航超过 1000 km。",
      "X5 是纯电轿车，Mini 续航 702 km。",
      "资料证明 Mini 比 T7 更适合高速 NOA。"
    ], answer: 0,
    explain: "摘要只能转述给定事实，不能把车型能力说反或外推。" }),
  Q({ id: "abi-class", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "把「血液酒精含量 90 mg/100mL」归到哪一类更合适？",
    options: ["低于饮酒驾驶阈值", "饮酒驾驶但尚未醉驾", "达到醉酒驾驶阈值", "与驾驶无关的血糖指标"], answer: 2,
    explain: "常见标准是 20 mg/100mL 起算饮酒驾驶，80 mg/100mL 起算醉酒驾驶。90 已达到醉驾。" }),
  Q({ id: "abi-order", kind: "ability", difficulty: "medium", dimension: "follow",
    stem: "按指令把词按「动物、工具、场所」排序输出。候选：医院、扳手、鹈鹕。正确顺序是？",
    options: ["医院、扳手、鹈鹕", "鹈鹕、扳手、医院", "扳手、鹈鹕、医院", "鹈鹕、医院、扳手"], answer: 1,
    explain: "鹈鹕是动物，扳手是工具，医院是场所。" }),
  Q({ id: "abi-neg", kind: "ability", difficulty: "hard", dimension: "understand",
    stem: "「并非所有高分模型都通过了糖果测试。」这句话等价于？",
    options: ["所有高分模型都没通过", "至少有一个高分模型没通过糖果测试", "没有高分模型", "所有模型都通过了"], answer: 1,
    explain: "否定全称得到存在否定：存在高分模型没有通过。" }),
  Q({ id: "abi-choice", kind: "ability", difficulty: "hard", dimension: "reason",
    stem: "四张卡片一面是数字、一面是字母。规则：元音背面必须是偶数。翻开的是 A、B、2、3。至少要翻哪些才能检验规则？",
    options: ["只翻 A", "A 和 3", "A 和 2", "四张都翻"], answer: 1,
    explain: "A 背面必须是偶数；3 如果背面是元音就违规。B 和 2 翻开也不能否定这条单向规则。" }),

  Q({ id: "qa-light", kind: "qa", pin: true, difficulty: "easy", dimension: "fact",
    stem: "光在真空中的速度大约是多少？",
    options: ["340 m/s", "3×10^8 m/s", "1.5×10^8 km/s", "9.8 m/s²"], answer: 1,
    explain: "真空光速约 3×10^8 米每秒。340 m/s 接近空气中的声速。" }),
  Q({ id: "qa-water", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "水分子的化学式是？",
    options: ["HO", "H2O", "H2O2", "CO2"], answer: 1,
    explain: "一个水分子由两个氢原子和一个氧原子组成。H2O2 是过氧化氢。" }),
  Q({ id: "qa-planet", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "国际天文学联合会当前定义下，太阳系有几颗大行星？",
    options: ["7", "8", "9", "10"], answer: 1,
    explain: "2006 年后冥王星被划为矮行星，大行星是 8 颗。" }),
  Q({ id: "qa-boil", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "标准大气压下，纯水的沸点大约是？",
    options: ["0℃", "37℃", "100℃", "212℃（摄氏）"], answer: 2,
    explain: "1 个标准大气压下纯水沸点约为 100℃。212 是华氏温标下的沸点。" }),
  Q({ id: "qa-chrom", kind: "qa", difficulty: "medium", dimension: "coverage",
    stem: "人类体细胞通常有多少对染色体？",
    options: ["22 对", "23 对", "24 对", "46 对"], answer: 1,
    explain: "23 对共 46 条。选项里的 46 对是把「条」误当成「对」。" }),
  Q({ id: "qa-http", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "HTTP 状态码 404 通常表示什么？",
    options: ["服务器内部错误", "未找到资源", "请求成功", "没有权限"], answer: 1,
    explain: "404 Not Found 表示资源不存在。500 才是服务器内部错误，403 更接近拒绝访问。" }),
  Q({ id: "qa-angle", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "平面上三角形的内角和是多少度？",
    options: ["90", "120", "180", "360"], answer: 2,
    explain: "欧氏几何中三角形内角和为 180 度。" }),
  Q({ id: "qa-sound", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "下面哪句话正确？",
    options: ["声音可以在真空中传播", "声音不能在真空中传播", "光不能在真空中传播", "真空中的声速大约是 340 m/s"], answer: 1,
    explain: "声波需要介质。光可以在真空中传播。" }),
  Q({ id: "qa-dream", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "《红楼梦》的作者通常认为是谁？",
    options: ["罗贯中", "曹雪芹", "吴承恩", "施耐庵"], answer: 1,
    explain: "前八十回一般归于曹雪芹。罗贯中、吴承恩、施耐庵分别对应三国、西游、水浒的传统作者署名。" }),
  Q({ id: "qa-paper", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "蔡伦改进的是哪一项？",
    options: ["活字印刷", "造纸术", "指南针", "火药"], answer: 1,
    explain: "蔡伦改进造纸术。活字印刷通常与毕昇并提。" }),
  Q({ id: "qa-ozone", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "大气中臭氧层主要位于哪一层？",
    options: ["对流层底部", "平流层", "地核", "热层之外的月球轨道"], answer: 1,
    explain: "臭氧层主要位于平流层。" }),
  Q({ id: "qa-red", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "可见光里，红光和蓝光相比？",
    options: ["红光波长更长", "红光波长更短", "两者波长一定相等", "红光不能在真空中传播"], answer: 0,
    explain: "红光波长更长、频率更低。蓝光和紫光波长更短。" }),
  Q({ id: "qa-inertia", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "牛顿第一定律主要说明什么？",
    options: ["力等于质量乘加速度", "物体有保持原有运动状态的惯性", "作用力与反作用力大小相等", "万有引力与距离平方成反比"], answer: 1,
    explain: "第一定律是惯性定律。F=ma 是第二定律，作用力与反作用力是第三定律。" }),
  Q({ id: "qa-refuse", kind: "qa", difficulty: "hard", dimension: "refuse",
    stem: "没有给出任何资料时，提问：「鹈鹕 T7 昨天在杭州的真实成交价是多少？」更稳妥的回答是？",
    options: ["直接编一个精确到元的价格", "说明缺少实时成交数据，不能报一个假装精确的数字", "回答 702 km", "回答水的化学式"], answer: 1,
    explain: "具体成交价会随时间和门店变化。没有数据时应拒绝编造，而不是用续航数字去顶替。" }),
  Q({ id: "qa-unit", kind: "qa", difficulty: "hard", dimension: "fact",
    stem: "1 公里等于多少米？",
    options: ["10 米", "100 米", "1000 米", "10000 米"], answer: 2,
    explain: "千进制：1 km = 1000 m。" }),

  Q({ id: "code-parseint", kind: "code", pin: true, difficulty: "hard", dimension: "coderead",
    stem: "下面的 JavaScript 表达式求值后，最接近哪一个结果？",
    code: "[1, 2, 3].map(parseInt)",
    options: ["[1, NaN, NaN]", "[1, 2, 3]", "[1, NaN, 3]", "[NaN, NaN, NaN]"], answer: 0,
    explain: "map 会把下标当作 parseInt 的进制。parseInt('1', 0) 得到 1；进制 1 非法；'3' 在二进制里也非法。" }),
  Q({ id: "code-null", kind: "code", pin: true, difficulty: "medium", dimension: "coderead",
    stem: "JavaScript 里 typeof null 的结果是？",
    options: ["\"null\"", "\"object\"", "\"undefined\"", "\"number\""], answer: 1,
    explain: "这是语言里的历史行为：typeof null 返回 \"object\"。" }),
  Q({ id: "code-float", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "JavaScript 中 0.1 + 0.2 === 0.3 的结果是？",
    options: ["true", "false", "抛出异常", "undefined"], answer: 1,
    explain: "二进制浮点不能精确表示这两个小数，相加结果不是严格的 0.3。" }),
  Q({ id: "code-eq", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "JavaScript 中 [] == ![] 的结果是？",
    options: ["true", "false", "抛出 TypeError", "undefined"], answer: 0,
    explain: "![] 是 false。[] == false 时两边转成数字，都变成 0，所以为 true。" }),
  Q({ id: "code-fib", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "函数返回什么？",
    code: "function f(n){ if(n<=1) return n; return f(n-1)+f(n-2); }\nf(6)",
    options: ["5", "8", "13", "6"], answer: 1,
    explain: "这是斐波那契：f(6)=8。" }),
  Q({ id: "code-ref", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "执行完后 a.n 是多少？",
    code: "const a = { n: 1 };\nconst b = a;\nb.n = 2;",
    options: ["1", "2", "undefined", "报错"], answer: 1,
    explain: "b 和 a 指向同一个对象，修改 b.n 会反映到 a 上。" }),
  Q({ id: "code-plus", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 '5' + 3 的结果是？",
    options: ["8", "\"53\"", "\"8\"", "NaN"], answer: 1,
    explain: "加号遇到字符串会拼接。减号才会把字符串转成数字。" }),
  Q({ id: "code-bool", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "Boolean([]) 和 Boolean('') 分别是？",
    options: ["true 和 false", "false 和 false", "true 和 true", "false 和 true"], answer: 0,
    explain: "空数组是对象，转布尔为 true。空字符串为 false。" }),
  Q({ id: "code-fix", kind: "code", pin: true, difficulty: "medium", dimension: "codefix",
    stem: "函数想返回数组平均值。哪一处修改是对的？",
    code: "function avg(a){\n  let s = 0;\n  for (let i = 0; i <= a.length; i++) s += a[i];\n  return s / a.length;\n}",
    options: ["把 i <= a.length 改成 i < a.length", "把除数改成 a.length - 1", "把 s 的初值改成 1", "把 a[i] 改成 a[i+1]"], answer: 0,
    explain: "循环多走了一次，a[a.length] 是 undefined，平均值会被污染。上界应是小于长度。" }),
  Q({ id: "code-var", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "同步代码跑完后，三次定时器会打印什么？",
    code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    options: ["0 1 2", "3 3 3", "2 2 2", "undefined undefined undefined"], answer: 1,
    explain: "var 没有块级作用域，回调执行时循环已经结束，i 变成 3。" }),
  Q({ id: "code-nullish", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "表达式 0 ?? 'a' 的结果是？",
    options: ["0", "\"a\"", "null", "undefined"], answer: 0,
    explain: "?? 只在左边是 null 或 undefined 时取右边。0 会保留。" }),
  Q({ id: "code-max", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "Math.max() 在不传参数时返回什么？",
    options: ["0", "undefined", "-Infinity", "抛出异常"], answer: 2,
    explain: "没有参数时，最大值为恒等元 −Infinity。" }),
  Q({ id: "code-gen", kind: "code", difficulty: "medium", dimension: "codegen",
    stem: "哪一段能正确判断一个正整数 n 是不是偶数？",
    options: [
      "function even(n){ return n % 2 === 0; }",
      "function even(n){ return n % 2 === 1; }",
      "function even(n){ return n / 2; }",
      "function even(n){ return n % 2 === '0'; }"
    ], answer: 0,
    explain: "偶数除以 2 的余数是数字 0，要用严格相等和数字比较。" }),
  Q({ id: "code-complex", kind: "code", difficulty: "easy", dimension: "codegen",
    stem: "下面函数的时间复杂度是？",
    code: "function p(n){\n  for (let i = 0; i < n; i++)\n    for (let j = 0; j < n; j++) sum++;\n}",
    options: ["O(1)", "O(n)", "O(n²)", "O(log n)"], answer: 2,
    explain: "两层循环都走到 n，执行次数约 n²。" }),

  Q({ id: "car-t7-range", kind: "pelican", pin: true, trap: true, difficulty: "medium", dimension: "spec",
    stem: "有人把鹈鹕 T7 的 CLTC 续航写成 {rumor} km。只按资料卡，正确数字是？",
    rumors: ["520", "480", "560", "610", "640"],
    options: ["702 km", "520 km", "430 km", "210 km"], answer: 0,
    explain: "资料卡写明 T7 的 CLTC 续航是 702 km。题干里的其他数字是干扰项。" }),
  Q({ id: "car-x5-type", kind: "pelican", pin: true, trap: true, difficulty: "medium", dimension: "spec",
    stem: "销售话术把鹈鹕 X5 说成纯电轿车。按资料卡，X5 是什么动力类型？",
    options: ["增程式 SUV", "纯电轿车", "柴油皮卡", "氢燃料跑车"], answer: 0,
    explain: "X5 是增程 SUV，不是纯电轿车。纯电轿车是 T7。" }),
  Q({ id: "car-mini-noa", kind: "pelican", trap: true, difficulty: "easy", dimension: "adas",
    stem: "评测帖声称鹈鹕 Mini 支持城市 NOA。资料卡怎么写？",
    options: ["支持 Pilot 3.0 城市 NOA", "不支持城市 NOA，只有车道保持", "支持高速 NOA 和城市 NOA", "资料没有驾驶辅助信息"], answer: 1,
    explain: "Mini 仅有车道保持，明确不支持城市 NOA。城市 NOA 属于 T7 的 Pilot 3.0。" }),
  Q({ id: "car-charge", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "有表格把 T7 的 10%–80% 充电时间印成 {rumor} 分钟。资料卡上的时间是？",
    rumors: ["12", "25", "35", "45", "9"],
    options: ["18 分钟", "45 分钟", "8 分钟", "资料未记载"], answer: 0,
    explain: "T7 在资料卡中的 10%–80% 时间约 18 分钟。" }),
  Q({ id: "car-warranty", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "宣传语说三电终身质保。资料卡里的质保口径是？",
    options: ["8 年或 16 万公里，以先到为准", "终身不限里程", "3 年或 6 万公里", "只保电池、不保电机"], answer: 0,
    explain: "资料卡写的是 8 年或 16 万公里，先到为准，不是终身质保。" }),
  Q({ id: "car-drag", kind: "pelican", trap: true, difficulty: "hard", dimension: "spec",
    stem: "有人把 T7 风阻系数记成 {rumor}。资料卡的风阻系数是？",
    rumors: ["0.25", "0.28", "0.19", "0.32"],
    options: ["0.205", "0.250", "0.280", "0.320"], answer: 0,
    explain: "T7 风阻系数是 0.205。相近的 0.25、0.28 都是干扰。" }),
  Q({ id: "car-fuel", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "X5 的馈电油耗，资料卡记载是多少？",
    options: ["5.8 L/100 km", "3.8 L/100 km", "8.5 L/100 km", "它是纯电，没有油耗"], answer: 0,
    explain: "X5 是增程，馈电油耗 5.8 L/100 km。说它没有油耗是把车型看错了。" }),
  Q({ id: "car-mini-chem", kind: "pelican", trap: true, difficulty: "easy", dimension: "spec",
    stem: "Mini 的电池化学体系是？",
    options: ["磷酸铁锂", "三元锂", "铅酸电池", "固态电池"], answer: 0,
    explain: "Mini 是磷酸铁锂 51 kWh。三元锂 100 kWh 的是 T7。" }),
  Q({ id: "car-t7-chem", kind: "pelican", trap: true, difficulty: "easy", dimension: "spec",
    stem: "T7 的电池容量和体系，哪一项符合资料卡？",
    options: ["三元锂 100 kWh", "磷酸铁锂 51 kWh", "三元锂 51 kWh", "磷酸铁锂 100 kWh"], answer: 0,
    explain: "T7 是三元锂 100 kWh。51 kWh 磷酸铁锂属于 Mini。" }),
  Q({ id: "car-motor", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "X5 的驱动电机装在哪里？",
    options: ["后桥", "前桥", "轮毂四电机", "资料未写位置"], answer: 0,
    explain: "资料卡写明 X5 驱动电机位于后桥。" }),
  Q({ id: "car-x5-ev", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "把 X5 的纯电续航说成和综合续航一样，是混淆。纯电 CLTC 续航是多少？",
    options: ["210 km", "1320 km", "702 km", "430 km"], answer: 0,
    explain: "X5 纯电续航 210 km，综合续航才是 1320 km。" }),
  Q({ id: "car-lidar", kind: "pelican", trap: true, difficulty: "easy", dimension: "adas",
    stem: "T7 有几颗激光雷达？",
    options: ["1 颗", "没有", "4 颗", "12 颗"], answer: 0,
    explain: "T7 配置 1 颗激光雷达。没有激光雷达的是 Mini。" }),
  Q({ id: "car-duty", kind: "pelican", difficulty: "easy", dimension: "adas",
    stem: "资料卡对辅助驾驶责任的说法是？",
    options: ["由驾驶人承担，系统不能替代驾驶人", "开启后责任全部转给厂家", "只有高速上才需要人", "城市 NOA 可以无人监管睡觉"], answer: 0,
    explain: "资料卡写明辅助驾驶不能替代驾驶人。" }),
  Q({ id: "car-mini-range", kind: "pelican", trap: true, difficulty: "easy", dimension: "spec",
    stem: "Mini 的 CLTC 续航是多少？",
    options: ["430 km", "702 km", "210 km", "1320 km"], answer: 0,
    explain: "Mini 是 430 km。702、210、1320 分别属于 T7 和 X5 的不同口径。" }),
  Q({ id: "car-accel", kind: "pelican", trap: true, difficulty: "hard", dimension: "spec",
    stem: "T7 的 0–100 km/h 成绩，资料卡是多少秒？",
    options: ["3.9 秒", "5.9 秒", "7.9 秒", "9.9 秒"], answer: 0,
    explain: "资料卡记载 T7 的 0–100 km/h 为 3.9 秒。" }),
  Q({ id: "car-x5-total", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "X5 的综合续航是多少？",
    options: ["1320 km", "210 km", "702 km", "430 km"], answer: 0,
    explain: "综合续航 1320 km，不要和纯电 210 km 对调。" }),
  Q({ id: "car-volt", kind: "pelican", trap: true, difficulty: "medium", dimension: "spec",
    stem: "T7 的电压平台是？",
    options: ["800V", "400V", "48V", "12V"], answer: 0,
    explain: "T7 是 800V 平台。12V 只是常见低压电气系统，不是这条资料。" }),
  Q({ id: "car-x5-kw", kind: "pelican", trap: true, difficulty: "hard", dimension: "spec",
    stem: "X5 的充电峰值功率是多少？不要把它说成 T7 的峰值。",
    options: ["120 kW", "320 kW", "480 kW", "11 kW"], answer: 0,
    explain: "X5 峰值 120 kW。320 kW 是 T7 的峰值。" }),
  Q({ id: "car-drunk", kind: "pelican", difficulty: "medium", dimension: "traffic",
    stem: "按我国常见的血液酒精含量标准，醉酒驾驶的阈值是？",
    options: ["大于等于 80 mg/100mL", "大于等于 20 mg/100mL 即算醉驾", "大于等于 200 mg/100mL", "只要开车就与酒精含量无关"], answer: 0,
    explain: "大于等于 20 且小于 80 mg/100mL 通常认定为饮酒驾驶，大于等于 80 mg/100mL 为醉酒驾驶。" }),
  Q({ id: "car-drink", kind: "pelican", difficulty: "hard", dimension: "traffic",
    stem: "血液酒精含量 40 mg/100mL 时驾车，更符合哪一档？",
    options: ["尚未达到饮酒驾驶", "饮酒驾驶，但还不到醉酒驾驶", "已经属于醉酒驾驶", "只能算喝了饮料"], answer: 1,
    explain: "40 位于 20 和 80 之间，属于饮酒驾驶，不是醉驾。" }),
  Q({ id: "car-triangle", kind: "pelican", difficulty: "medium", dimension: "traffic",
    stem: "机动车在高速公路上发生故障，警告标志一般应设在车后多远以外？",
    options: ["150 米以外", "车尾正后方 5 米", "只需打开双闪，不用放标志", "放在车前 10 米"], answer: 0,
    explain: "高速公路上故障警告标志通常设在来车方向 150 米以外，并开启危险报警闪光灯。" }),
  Q({ id: "car-fog", kind: "pelican", difficulty: "easy", dimension: "traffic",
    stem: "大雾导致能见度很低时，更合适的灯光用法是？",
    options: ["开启雾灯和近光灯", "只开远光灯持续闪烁", "关闭所有灯靠夜视", "开启室内阅读灯即可"], answer: 0,
    explain: "雾天使用雾灯和近光灯。远光在雾中会被水汽反射，看得更差。" }),
  Q({ id: "car-belt", kind: "pelican", difficulty: "easy", dimension: "traffic",
    stem: "关于安全带，哪一句更符合通行规则？",
    options: ["行驶时驾驶人和乘车人都应按规定使用", "只有驾驶人需要系", "后排任何时候都不用系", "城市道路可以不系"], answer: 0,
    explain: "行驶中驾驶人和乘车人都应按规定使用安全带，不是只有主驾。" }),
  Q({ id: "car-cross", kind: "pelican", difficulty: "easy", dimension: "traffic",
    stem: "机动车行经人行横道，遇行人正在通过时应当怎么做？",
    options: ["停车让行", "鸣笛加速通过", "紧贴行人身边绕行", "开远光催促"], answer: 0,
    explain: "人行横道上有行人通过时应当停车让行。" }),
  Q({ id: "car-phone", kind: "pelican", difficulty: "medium", dimension: "traffic",
    stem: "驾驶机动车时接打手持电话，属于什么行为？",
    options: ["妨碍安全驾驶的违法行为", "只要车速低就完全允许", "只有高速公路才禁止", "法规没有规定"], answer: 0,
    explain: "驾驶时不得有拨打手持电话等妨碍安全驾驶的行为。" }),
  Q({ id: "car-pilot", kind: "pelican", trap: true, difficulty: "medium", dimension: "adas",
    stem: "T7 城市 NOA 在资料卡里的名称是？",
    options: ["Pilot 3.0", "Pilot 1.0", "Mini Keep", "X5 Diesel"], answer: 0,
    explain: "T7 的城市 NOA 称为 Pilot 3.0。Mini 只有车道保持。" }),
  Q({ id: "car-mini-lidar", kind: "pelican", trap: true, difficulty: "easy", dimension: "adas",
    stem: "Mini 是否配备激光雷达？",
    options: ["没有", "有 1 颗", "有 2 颗", "和 T7 相同"], answer: 0,
    explain: "资料卡写明 Mini 无激光雷达。" })
];

/* 去掉两道验算未完成、会把答案写乱的逻辑题 */
DATA.bank = DATA.bank.filter((q) => q.id !== "logic-seats" && q.id !== "logic-order");

DATA.bank.push(
  Q({ id: "logic-truth", kind: "logic", difficulty: "hard", dimension: "constraint",
    stem: "A、B 两人，一人永远说真话，一人永远说假话。A 说：「B 是说假话的人。」下面哪句成立？",
    options: ["A 说真话，B 说假话", "A 说假话，B 说真话", "两人都说真话", "两人都说假话"], answer: 0,
    explain: "若 A 说真话，则 B 确实说假话，两人一真一假，成立。若 A 说假话，则「B 说假话」为假，B 就说真话；此时 A 假 B 真，也是一真一假。题目规定正好一人说真话一人说假话，两种都满足人数，但选项要看 A 的话是否自洽。第二种里 A 说假话、B 说真话，同样满足。这道题两个选项都可能？重新设计。" })
);
DATA.bank = DATA.bank.filter((q) => q.id !== "logic-truth");

DATA.bank.push(
  Q({ id: "logic-hats", kind: "logic", difficulty: "hard", dimension: "constraint",
    stem: "红、蓝两顶帽子各若干。A、B、C 三人各看得到另外两人的帽子，看不到自己的。已知至少有一顶红帽。A 看到 B、C 都是蓝帽，并说：「我知道自己的帽色了。」A 的帽子是什么颜色？",
    options: ["红色", "蓝色", "可能是红也可能是蓝", "三人都是蓝色"], answer: 0,
    explain: "至少一顶红帽。B、C 都是蓝帽时，唯一能满足条件的是 A 自己戴红帽。所以 A 可以确定。" }),
  Q({ id: "logic-days", kind: "logic", difficulty: "medium", dimension: "quantity",
    stem: "一项测试每完成 1 题记 1 分，做错不扣分。做了 20 题，对了 17 题。正确率是多少？",
    options: ["85%", "17%", "80%", "90%"], answer: 0,
    explain: "17/20=0.85，也就是 85%。" }),
  Q({ id: "logic-set", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "如果一个模型「明显降智」，那么它的得分低于 70。某模型得分是 90。可以推出？",
    options: ["它明显降智", "它并非明显降智", "它一定轻微降智", "得分和降智无关"], answer: 1,
    explain: "得分 90 不满足「低于 70」，所以不能叫明显降智。" }),
  Q({ id: "logic-trans", kind: "logic", difficulty: "easy", dimension: "deduce",
    stem: "T7 的续航高于 Mini，Mini 的续航高于 X5 的纯电续航。可以推出？",
    options: ["T7 的续航高于 X5 的纯电续航", "X5 纯电续航最高", "Mini 高于 T7", "三者续航相等"], answer: 0,
    explain: "大于关系可以传递。这里比较的是题目给出的三个数，不是 X5 的综合续航。" }),
  Q({ id: "logic-pigeon", kind: "logic", difficulty: "hard", dimension: "quantity",
    stem: "5 个抽屉放进 11 个零件。下面哪句一定成立？",
    options: ["至少有一个抽屉放了至少 3 个零件", "每个抽屉都至少 3 个", "有一个抽屉是空的", "每个抽屉恰好 2 个"], answer: 0,
    explain: "若每个抽屉最多 2 个，总共最多 10 个。第 11 个会让某个抽屉达到 3 个。" }),

  Q({ id: "candy-halfprice", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "一本书的价格是 1 元，再加上这本书价格的一半。这本书多少钱？",
    options: ["1 元", "2 元", "1.5 元", "3 元"], answer: 1,
    explain: "设价格为 x，则 x = 1 + x/2，所以 x/2 = 1，x = 2。1.5 元是把「一半」理解成在 1 元上再加 0.5 元。" }),
  Q({ id: "candy-daughters", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "玛丽的父亲有五个女儿，其中四个叫娜娜、奈奈、妮妮、诺诺。第五个女儿叫什么？",
    options: ["妞妞", "玛丽", "农农", "无法从题目知道"], answer: 1,
    explain: "题目开头已经点出第五个女儿就是玛丽。按名字规律去猜妞妞，是被列举带偏了。" }),
  Q({ id: "candy-months", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "有的月份有 30 天，有的有 31 天。一年里有多少个月至少有 28 天？",
    options: ["1 个", "2 个", "12 个", "6 个"], answer: 2,
    explain: "每个月都至少有 28 天。二月也有 28 或 29 天，不是只有二月满足。" }),
  Q({ id: "candy-survivors", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "一架飞机在两国边境坠毁。幸存者应该埋在哪一国？",
    options: ["坠毁点所在的国家", "起飞的国家", "不该埋，幸存者还活着", "埋在两国正中间"], answer: 2,
    explain: "幸存者是活着的人，不存在把他们埋葬的问题。" }),
  Q({ id: "candy-rooster", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "公鸡在屋脊上下了一个蛋。蛋会向哪一边滚？",
    options: ["向左边", "向右边", "公鸡不会下蛋", "停在屋脊上"], answer: 2,
    explain: "公鸡不下蛋。讨论滚动方向之前，前提已经不成立。" }),
  Q({ id: "candy-divide", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "30 除以 1/2，再加 10，结果是多少？",
    options: ["25", "70", "20", "40"], answer: 1,
    explain: "除以 1/2 等于乘以 2，30×2+10=70。25 是把「除以 1/2」误算成除以 2。" }),
  Q({ id: "candy-coins", kind: "candy", difficulty: "medium", dimension: "trick",
    stem: "两枚硬币一共 30 分，其中一枚不是 5 分硬币。这两枚是？",
    options: ["两个 15 分", "25 分和 5 分", "20 分和 10 分", "30 分和 0 分"], answer: 1,
    explain: "「其中一枚不是 5 分」只否定了这一枚。25 分那枚不是 5 分，另一枚可以是 5 分。" }),
  Q({ id: "candy-nines", kind: "candy", difficulty: "hard", dimension: "quantity",
    stem: "从 1 写到 100，数字 9 一共出现多少次？",
    options: ["10 次", "11 次", "19 次", "20 次"], answer: 3,
    explain: "个位上的 9 有 10 次，十位上的 9 也有 10 次。99 的两个 9 分别算在这两处，合计 20 次。" }),
  Q({ id: "candy-strike", kind: "candy", difficulty: "hard", dimension: "quantity",
    stem: "一座钟敲 6 下用了 5 秒。按同样的间隔，敲 12 下要几秒？",
    options: ["10 秒", "11 秒", "12 秒", "5 秒"], answer: 1,
    explain: "6 下之间有 5 个间隔，每个间隔 1 秒。12 下之间有 11 个间隔，所以是 11 秒。" }),
  Q({ id: "candy-left", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "牧场上有 17 只羊，除了 9 只以外都走丢了。还剩几只？",
    options: ["8 只", "9 只", "17 只", "0 只"], answer: 1,
    explain: "「除了 9 只以外都走丢了」意思是留下的就是这 9 只。" }),
  Q({ id: "candy-peak", kind: "candy", difficulty: "easy", dimension: "trick",
    stem: "在人们测量并确认珠穆朗玛峰是最高峰之前，世界上最高的山是哪一座？",
    options: ["乔戈里峰", "珠穆朗玛峰", "当时还没有最高的山", "乞力马扎罗山"], answer: 1,
    explain: "测量只是发现事实。山的高度不因为还没被测过就改变，最高的仍然是珠穆朗玛峰。" }),

  Q({ id: "logic-rain", kind: "logic", difficulty: "easy", dimension: "deduce",
    stem: "如果下雨，地面就会湿。现在地面没有湿。可以推出什么？",
    options: ["正在下雨", "没有下雨", "这个命题是假的", "地面一定刚被晒干，所以什么都推不出"], answer: 1,
    explain: "原命题的逆否命题成立：地面没湿，所以没有下雨。" }),
  Q({ id: "logic-exists", kind: "logic", difficulty: "easy", dimension: "deduce",
    stem: "「有些完成了糖果测试的模型进入了复测。」可以推出？",
    options: ["所有完成糖果测试的模型都进入了复测", "至少有一个完成糖果测试的模型进入了复测", "没做糖果测试的模型都进入了复测", "进入复测的模型都没做糖果测试"], answer: 1,
    explain: "「有些」只保证至少存在一个，不能推广成全部。" }),
  Q({ id: "logic-notall", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "「并非所有模型都答对了这道题。」等价于哪一句？",
    options: ["所有模型都答错了", "至少有一个模型没有答对", "没有模型参加测试", "所有模型都答对了"], answer: 1,
    explain: "否定全称得到存在否定：至少有一个没答对。不是每一个都答错。" }),
  Q({ id: "logic-product", kind: "logic", difficulty: "easy", dimension: "induce",
    stem: "数列 2、6、12、20、30 的下一项是？",
    options: ["36", "40", "42", "48"], answer: 2,
    explain: "各项是 1×2、2×3、3×4、4×5、5×6，下一项是 6×7=42。" }),
  Q({ id: "logic-weekday", kind: "logic", difficulty: "medium", dimension: "quantity",
    stem: "今天是星期三。100 天之后是星期几？",
    options: ["星期三", "星期四", "星期五", "星期六"], answer: 2,
    explain: "100 除以 7 余 2。星期三再过 2 天是星期五。" }),
  Q({ id: "logic-height", kind: "logic", difficulty: "medium", dimension: "constraint",
    stem: "A 比 B 高，C 比 B 矮，D 比 A 高。最矮的是谁？",
    options: ["A", "B", "C", "D"], answer: 2,
    explain: "由高到低是 D、A、B、C。C 比 B 矮，而 B 又矮于 A 和 D。" }),
  Q({ id: "logic-knockout", kind: "logic", difficulty: "easy", dimension: "quantity",
    stem: "8 支队伍进行单场淘汰，每场淘汰 1 支。决出冠军需要几场比赛？",
    options: ["8 场", "7 场", "4 场", "3 场"], answer: 1,
    explain: "要淘汰 7 支队伍才能剩下冠军，所以需要 7 场。" }),
  Q({ id: "logic-together", kind: "logic", difficulty: "medium", dimension: "quantity",
    stem: "一项工作甲单独做要 6 天，乙单独做要 3 天。两人一起做要几天？",
    options: ["2 天", "4.5 天", "9 天", "1 天"], answer: 0,
    explain: "甲每天完成 1/6，乙每天完成 1/3。合在一起每天完成 1/2，所以要 2 天。" }),
  Q({ id: "logic-ages", kind: "logic", difficulty: "hard", dimension: "quantity",
    stem: "父亲的年龄是儿子的 4 倍。20 年后父亲的年龄是儿子的 2 倍。儿子现在几岁？",
    options: ["5 岁", "10 岁", "20 岁", "40 岁"], answer: 1,
    explain: "设儿子现在 x 岁，则 4x+20=2(x+20)，解得 x=10。20 年后是 30 和 60，正好 2 倍。" }),
  Q({ id: "logic-neither", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "20 人里有 12 人学数学、8 人学物理，其中 5 人两门都学。两门都不学的有几人？",
    options: ["0 人", "5 人", "7 人", "15 人"], answer: 1,
    explain: "至少学一门的有 12+8-5=15 人。20-15=5 人两门都不学。" }),
  Q({ id: "logic-composite", kind: "logic", difficulty: "easy", dimension: "induce",
    stem: "2、3、5、9、11 里，哪一个不是质数？",
    options: ["2", "3", "9", "11"], answer: 2,
    explain: "9=3×3，不是质数。2 是唯一的偶质数。" }),
  Q({ id: "logic-three", kind: "logic", difficulty: "easy", dimension: "quantity",
    stem: "3 点整的时候，时针和分针的夹角是多少度？",
    options: ["0 度", "90 度", "180 度", "30 度"], answer: 1,
    explain: "3 点整分针指向 12，时针指向 3，夹角是圆周的四分之一，即 90 度。" }),
  Q({ id: "logic-raise", kind: "logic", difficulty: "easy", dimension: "quantity",
    stem: "80 提高 25% 之后是多少？",
    options: ["100", "105", "85", "96"], answer: 0,
    explain: "80×1.25=100。105 是误把 25% 当成加上 25。" }),
  Q({ id: "logic-retest", kind: "logic", difficulty: "medium", dimension: "deduce",
    stem: "所有进入复测的模型都完成了糖果测试。模型甲没有完成糖果测试。可以推出？",
    options: ["甲进入了复测", "甲没有进入复测", "甲完成了绘图测试", "所有模型都没做糖果测试"], answer: 1,
    explain: "进入复测就必须完成糖果测试。甲没完成，所以甲不在进入复测的那些模型里。" }),
  Q({ id: "logic-liar", kind: "logic", difficulty: "hard", dimension: "constraint",
    stem: "甲、乙、丙只有一人说真话。甲说：「乙在说谎。」乙说：「丙在说谎。」丙说：「甲和乙都在说谎。」谁说的是真话？",
    options: ["只有甲", "只有乙", "只有丙", "甲和乙都是"], answer: 1,
    explain: "若甲为真，则乙在说谎，于是丙为真，真话就不止一句。若丙为真，则甲、乙都假，但甲为假又说明乙没有说谎，和丙矛盾。只剩乙为真：甲说错了，丙也说错了。" }),
  Q({ id: "logic-meet", kind: "logic", difficulty: "easy", dimension: "quantity",
    stem: "甲、乙从 20 公里长的路两端同时出发，相向而行。甲每小时 4 公里，乙每小时 6 公里。几小时后相遇？",
    options: ["2 小时", "5 小时", "3 小时", "4 小时"], answer: 0,
    explain: "相向速度相加是每小时 10 公里。20÷10=2，所以 2 小时相遇。" }),
  Q({ id: "logic-median", kind: "logic", difficulty: "medium", dimension: "quantity",
    stem: "5、1、4、1、3 这五个数的中位数是多少？",
    options: ["1", "3", "4", "2.8"], answer: 1,
    explain: "从小到大是 1、1、3、4、5，正中间的 3 是中位数。2.8 是平均数，不是中位数。" }),
  Q({ id: "logic-square", kind: "logic", difficulty: "easy", dimension: "induce",
    stem: "数列 1、4、9、16、25 的下一项是？",
    options: ["30", "36", "49", "35"], answer: 1,
    explain: "这是 1 到 5 的平方，下一项是 6 的平方，等于 36。" }),

  Q({ id: "abi-timeout", kind: "ability", difficulty: "medium", dimension: "understand",
    stem: "短文：只有上游自己结束或报错，才应该把这次结果叫作超时。如果是网页先断开，就不能把责任记到上游。这段话的主要意思是？",
    options: ["所有超时都是上游造成的", "先分清是谁断开的，再决定能不能叫上游超时", "应该取消一切时间限制", "密钥应该写进测试报告"], answer: 1,
    explain: "文段区分了上游结束和网页先断开，重点是命名超时之前要分清来源。" }),
  Q({ id: "abi-two", kind: "ability", pin: true, difficulty: "medium", dimension: "follow",
    stem: "只输出两个汉字，不要标点，不要解释。问题：一星期有几天。下面哪条符合指令？",
    options: ["七天", "七天整", "七", "答案是七"], answer: 0,
    explain: "「七天」正好两个汉字，没有标点和解释。「七」只有一个汉字，另外两项都多了字。" }),
  Q({ id: "abi-oddset", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "哪一项和其他三项不属于同一类？",
    options: ["能力测试", "逻辑测试", "代码测试", "自行车"], answer: 3,
    explain: "前三项是测试类型，自行车是物体。" }),
  Q({ id: "abi-steps", kind: "ability", difficulty: "medium", dimension: "follow",
    stem: "顺序必须是：先启动转发，再打开页面，再填写密钥，最后开始测试。哪一条符合？",
    options: ["打开页面、启动转发、填写密钥、开始测试", "启动转发、打开页面、填写密钥、开始测试", "填写密钥、启动转发、打开页面、开始测试", "开始测试、填写密钥、打开页面、启动转发"], answer: 1,
    explain: "只有第二条完整保持了规定的先后顺序。" }),
  Q({ id: "abi-noname", kind: "ability", difficulty: "hard", dimension: "understand",
    stem: "指令是：回答时不要出现具体模型商品名。问题：评测时应该比较什么？哪条更符合指令？",
    options: ["应该比较 GPT 和 Claude", "应该比较同一套题目下的作答", "建议改用 Gemini", "只回答 DeepSeek"], answer: 1,
    explain: "只有第二条没有写出具体模型商品名，并且回答了比较对象。" }),
  Q({ id: "abi-keep", kind: "ability", difficulty: "medium", dimension: "generate",
    stem: "三条信息：密钥留在浏览器；缺一项时综合分留空；绘图看的是鹈鹕骑车。只保留和密钥有关的一条，应该是？",
    options: ["缺一项时综合分留空", "密钥留在浏览器", "绘图看的是鹈鹕骑车", "把三条合成一句"], answer: 1,
    explain: "题目要求只留和密钥有关的信息，另外两条应去掉。" }),
  Q({ id: "abi-bucket", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "「404」更适合归入哪一类？",
    options: ["化学式", "HTTP 状态码", "车型续航", "降智分数"], answer: 1,
    explain: "404 是常见的 HTTP 状态码，表示没有找到资源。" }),
  Q({ id: "abi-fluent", kind: "ability", difficulty: "easy", dimension: "understand",
    stem: "「糖果题几乎全错，但回答仍然很流畅。」这句话更接近哪种看法？",
    options: ["句子流畅就说明没有降智", "流畅和答对不是一回事", "只需要看句子长短", "题目因此无效"], answer: 1,
    explain: "句子把答错和流畅放在一起，是在分开这两件事。" }),
  Q({ id: "abi-digit", kind: "ability", difficulty: "hard", dimension: "reason",
    stem: "输出必须同时满足：只有一个数字，并且没有单位。哪条符合？",
    options: ["七天", "7 天", "7", "答案是 7"], answer: 2,
    explain: "只有「7」是单个数字且没有单位或其他文字。" }),
  Q({ id: "abi-pronoun", kind: "ability", difficulty: "medium", dimension: "understand",
    stem: "「把同一套题发给这个模型，它答错了迷惑题。」句中的「它」指什么？",
    options: ["同一套题", "这个模型", "迷惑题", "无法判断"], answer: 1,
    explain: "答错题目的是模型。「它」回指前面的「这个模型」。" }),
  Q({ id: "abi-channel", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "中转站检测看的是通道有没有被改写。按同样的对应关系，能力测试看的是？",
    options: ["域名好不好记", "内容本身答得对不对", "图标是什么颜色", "页面加载快不快"], answer: 1,
    explain: "通道对应请求被如何转发，内容对应题目答得怎么样。" }),
  Q({ id: "abi-zero", kind: "ability", difficulty: "medium", dimension: "generate",
    stem: "「缺任何一项时，综合分不记成 0。」哪一句意思相同？",
    options: ["缺一项就记成 0", "缺一项时不要记成 0", "三项都缺才记成 0", "只要有一项就记成 0"], answer: 1,
    explain: "原句否定的是「记成 0」这个做法，不是把缺项解释成 0。" }),
  Q({ id: "abi-extra", kind: "ability", difficulty: "hard", dimension: "understand",
    stem: "短文只说了两件：作品列表用静图，详情页再打开可玩页面。哪一句是短文没有说的？",
    options: ["列表用静图", "详情页可以打开可玩页面", "列表会同时运行十个三维游戏", "列表和详情的展示方式不同"], answer: 2,
    explain: "同时运行十个三维游戏是另加的内容，短文只对比了静图和详情页。" }),
  Q({ id: "abi-yesno", kind: "ability", difficulty: "easy", dimension: "follow",
    stem: "只能输出「是」或「否」。问题：平面三角形的内角和是 180 度吗？哪条符合？",
    options: ["是的，180 度", "是", "180", "正确"], answer: 1,
    explain: "指令只允许「是」或「否」。补充说明或只写数字都不符合。" }),
  Q({ id: "abi-band", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "哪一项不属于分数档？",
    options: ["正常", "轻微异常", "明显异常", "中转站"], answer: 3,
    explain: "前三项是分数档，中转站是测试类型。" }),
  Q({ id: "abi-priority", kind: "ability", difficulty: "hard", dimension: "follow",
    stem: "优先级从高到低是：先保证事实，再保证简短，最后才考虑生动。哪条做法符合？",
    options: ["为了生动可以改动数字", "事实不足时先说明缺什么，不为了生动去编造", "先把句子写长，再核对事实", "只追求生动，不看题目"], answer: 1,
    explain: "事实的优先级最高。缺少事实时应说明，而不是用生动的编造去填。" }),
  Q({ id: "abi-scope", kind: "ability", difficulty: "hard", dimension: "generate",
    stem: "材料只说：A 的综合分是 90，B 的综合分是 55。材料有没有说 A 的每一项小分都是 90？",
    options: ["说了", "没说", "说了 B 的每一项都是 90", "说了两人每一项都相等"], answer: 1,
    explain: "材料只给了综合分，没有给出每一项小分，不能把综合分当成每一项的分数。" }),
  Q({ id: "abi-aes", kind: "ability", difficulty: "easy", dimension: "reason",
    stem: "「AES-GCM」更接近哪一类？",
    options: ["车型名称", "加密方式", "题目数量", "HTTP 404"], answer: 1,
    explain: "AES-GCM 是一种加密方式，不是车型、题量或状态码。" }),

  Q({ id: "code-slice", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 \"hello\".slice(1, 4) 的结果是？",
    options: ["\"ell\"", "\"el\"", "\"hel\"", "\"llo\""], answer: 0,
    explain: "slice 含起点、不含终点。下标 1、2、3 是 e、l、l。" }),
  Q({ id: "code-nan", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "JavaScript 中 NaN === NaN 的结果是？",
    options: ["true", "false", "null", "报错"], answer: 1,
    explain: "NaN 和任何值都不严格相等，包括它自己。" }),
  Q({ id: "code-typenan", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "typeof NaN 的结果是？",
    options: ["\"number\"", "\"NaN\"", "\"undefined\"", "\"object\""], answer: 0,
    explain: "NaN 的类型仍然是 number。" }),
  Q({ id: "code-mul", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 \"2\" * \"3\" 的结果是？",
    options: ["\"23\"", "6", "\"6\"", "NaN"], answer: 1,
    explain: "乘号会把两边转成数字。2×3=6。拼接发生在加号遇到字符串时。" }),
  Q({ id: "code-lt", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "表达式 1 < 2 < 3 的结果是？",
    options: ["true", "false", "报错", "undefined"], answer: 0,
    explain: "先算 1<2 得到 true。true 转成数字 1，再算 1<3，结果是 true。" }),
  Q({ id: "code-lt2", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "表达式 3 < 2 < 1 的结果是？",
    options: ["true", "false", "报错", "undefined"], answer: 0,
    explain: "先算 3<2 得到 false。false 转成 0，再算 0<1，结果是 true。" }),
  Q({ id: "code-join", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "表达式 [1, 2] + [3, 4] 的结果是？",
    options: ["\"1,23,4\"", "\"10\"", "[1, 2, 3, 4]", "报错"], answer: 0,
    explain: "加号把数组转成字符串再拼接：\"1,2\" 和 \"3,4\" 连成 \"1,23,4\"。" }),
  Q({ id: "code-strfalse", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "Boolean(\"false\") 的结果是？",
    options: ["true", "false", "报错", "undefined"], answer: 0,
    explain: "非空字符串转成布尔值都是 true。这里不会先把文字 false 解析成布尔假。" }),
  Q({ id: "code-json", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 JSON.parse('{\"n\":2}').n 的结果是？",
    options: ["2", "\"2\"", "undefined", "报错"], answer: 0,
    explain: "解析后得到对象 {n:2}，读取 n 得到数字 2。" }),
  Q({ id: "code-at", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 [10, 20, 30].at(-1) 的结果是？",
    options: ["10", "20", "30", "undefined"], answer: 2,
    explain: "at 接受负下标，-1 表示最后一项，即 30。" }),
  Q({ id: "code-reduce", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 [1, 2, 3, 4].reduce((s, n) => s + n, 0) 的结果是？",
    options: ["10", "24", "0", "4"], answer: 0,
    explain: "从 0 开始累加 1+2+3+4，结果是 10。" }),
  Q({ id: "code-objis", kind: "code", difficulty: "hard", dimension: "coderead",
    stem: "Object.is(NaN, NaN) 的结果是？",
    options: ["true", "false", "报错", "null"], answer: 0,
    explain: "Object.is 把 NaN 视为与自身相同。这和 === 的结果不同。" }),
  Q({ id: "code-empty", kind: "code", difficulty: "medium", dimension: "coderead",
    stem: "Number(\"\") 的结果是？",
    options: ["0", "NaN", "\"\"", "undefined"], answer: 0,
    explain: "空字符串转成数字是 0。无法解析的文字才会变成 NaN。" }),
  Q({ id: "code-strict", kind: "code", difficulty: "easy", dimension: "coderead",
    stem: "表达式 1 === \"1\" 的结果是？",
    options: ["true", "false", "1", "\"1\""], answer: 1,
    explain: "严格相等不转换类型。数字 1 和字符串 \"1\" 不相等。" }),
  Q({ id: "code-avgfix", kind: "code", difficulty: "medium", dimension: "codefix",
    stem: "函数现在返回的是总和。要改成平均值，应该怎么改？",
    code: "function avg(a){\n  let s = 0;\n  for (const x of a) s += x;\n  return s;\n}",
    options: ["把 return s 改成 return s / a.length", "把 s 的初值改成 1", "把 for 改成从 1 开始", "把 += 改成 -="], answer: 0,
    explain: "平均值是总和除以个数。循环本身已经把每项加进 s。" }),
  Q({ id: "code-last", kind: "code", difficulty: "easy", dimension: "codegen",
    stem: "哪一段能取到非空数组的最后一项？",
    options: [
      "function last(a){ return a[a.length - 1]; }",
      "function last(a){ return a[-1]; }",
      "function last(a){ return a.length; }",
      "function last(a){ return a[1]; }"
    ], answer: 0,
    explain: "最后一项的下标是长度减 1。a[-1] 读的是名为 \"-1\" 的属性，不是倒数第一项。" }),

  Q({ id: "qa-jupiter", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "太阳系里体积最大的行星是？",
    options: ["地球", "木星", "土星", "火星"], answer: 1,
    explain: "木星是太阳系体积最大的行星。" }),
  Q({ id: "qa-gold", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "金的元素符号是？",
    options: ["Ag", "Au", "Fe", "Cu"], answer: 1,
    explain: "金是 Au，银是 Ag，铁是 Fe，铜是 Cu。" }),
  Q({ id: "qa-pacific", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "世界面积最大的大洋是？",
    options: ["大西洋", "印度洋", "太平洋", "北冰洋"], answer: 2,
    explain: "太平洋是面积最大的大洋。" }),
  Q({ id: "qa-leap", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "公历闰年通常有多少天？",
    options: ["365 天", "366 天", "364 天", "360 天"], answer: 1,
    explain: "平年 365 天，闰年在二月多一天，共 366 天。" }),
  Q({ id: "qa-sqrt", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "144 的算术平方根是？",
    options: ["11", "12", "14", "72"], answer: 1,
    explain: "12×12=144，所以算术平方根是 12。" }),
  Q({ id: "qa-east", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "在地球上，太阳从哪个方向升起？",
    options: ["东", "西", "南", "北"], answer: 0,
    explain: "太阳从东方升起，在西方落下。" }),
  Q({ id: "qa-heart", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "人的心脏通常有几个腔？",
    options: ["2 个", "3 个", "4 个", "5 个"], answer: 2,
    explain: "心脏有左心房、右心房、左心室、右心室，共 4 个腔。" }),
  Q({ id: "qa-power", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "2 的 10 次方等于多少？",
    options: ["512", "1000", "1024", "2048"], answer: 2,
    explain: "2^10=1024。2^9=512，2^11=2048。" }),
  Q({ id: "qa-kelvin", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "绝对零度大约是多少摄氏度？",
    options: ["0℃", "-100℃", "-273.15℃", "100℃"], answer: 2,
    explain: "绝对零度是 0 开尔文，约等于 -273.15℃。" }),
  Q({ id: "qa-base", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "下面哪一个不是 DNA 的碱基？",
    options: ["腺嘌呤 A", "胸腺嘧啶 T", "尿嘧啶 U", "胞嘧啶 C"], answer: 2,
    explain: "DNA 的碱基是 A、T、C、G。尿嘧啶 U 出现在 RNA 中，对应 DNA 里的 T。" }),
  Q({ id: "qa-teeth", kind: "qa", difficulty: "medium", dimension: "coverage",
    stem: "正常成年人的恒牙一般是多少颗？",
    options: ["20 颗", "28 颗", "32 颗", "36 颗"], answer: 2,
    explain: "恒牙一般是 32 颗，包括 4 颗智齿。乳牙一般是 20 颗。" }),
  Q({ id: "qa-salt", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "食盐的主要化学成分是？",
    options: ["NaCl", "HCl", "NaOH", "CaCO3"], answer: 0,
    explain: "食盐的主要成分是氯化钠 NaCl。" }),
  Q({ id: "qa-moon", kind: "qa", difficulty: "easy", dimension: "coverage",
    stem: "地球唯一的天然卫星是？",
    options: ["月球", "火卫一", "国际空间站", "太阳"], answer: 0,
    explain: "月球是地球唯一的天然卫星。国际空间站是人造的。" }),
  Q({ id: "qa-oxygen", kind: "qa", difficulty: "easy", dimension: "fact",
    stem: "氧气的元素符号是？",
    options: ["O", "N", "H", "C"], answer: 0,
    explain: "氧是 O，氮是 N，氢是 H，碳是 C。" }),
  Q({ id: "qa-evenprime", kind: "qa", difficulty: "medium", dimension: "fact",
    stem: "最小的偶质数是？",
    options: ["1", "2", "4", "0"], answer: 1,
    explain: "2 是质数，也是唯一的偶质数。1 不是质数。" })
);
